Added i18n documentation page
devonfw/java pull request #2
Opened 2022-10-25 08:44 UTC by RichardLinde

2022-10-26 14:06 UTC, baumeister25 requested changes
Awesome!
Just one minor point I found.

2022-10-26 14:06 UTC, baumeister25 commented on modules/ROOT/pages/cross_cutting/i18n.adoc
> +bookingDateShort=Your table is booked at {bookingDate, date, short}. <1>
Sry, I hate being picky with that, but here it should be bookingDateLong and the pattern in the end need the same addition.

2022-10-28 07:14 UTC, SchettlerKoehler requested changes

2022-10-28 11:41 UTC, baumeister25 approved these changes

2022-11-04 09:08 UTC, SchettlerKoehler approved these changes

2022-11-04 09:08 UTC, merged